
@startuml
:Timer settings for 10 ms
(Psc:3199 Arr:100 );
!pragma useVerticalIf on
start
noteleft:sevenseg_display(a)
if (a==0) then (yes)
  :SEG_A = SET
  SEG_B = SET
  SEG_C = SET
  SEG_D = SET
  SEG_E = SET
  SEG_F = SET
  SEG_G = RESET;
  stop
elseif (a==1) then (yes)
  :SEG_A = RESET
  SEG_B = SET
  SEG_C = SET
  SEG_D = RESET
  SEG_E = RESET
  SEG_F = RESET
  SEG_G = RESET;
  stop
elseif (a==2) then (yes)
  :SEG_A = RESET
  SEG_B = RESET
  SEG_C = SET
  SEG_D = RESET
  SEG_E = RESET
  SEG_F = SET
  SEG_G = RESET;
  stop;
elseif (a==3) then (yes)
  :SEG_A = SET
  SEG_B = SET
  SEG_C = SET
  SEG_D = SET
  SEG_E = RESET
  SEG_F = RESET
  SEG_G = SET;
  stop;
elseif (a==4) then (yes)
  :SEG_A = RESET
  SEG_B = SET
  SEG_C = SET
  SEG_D = RESET
  SEG_E = RESET
  SEG_F = SET
  SEG_G = SET;
  stop;
  elseif (a==5) then (yes)
  :SEG_A = SET
  SEG_B = RESET
  SEG_C = SET
  SEG_D = SET
  SEG_E = RESET
  SEG_F = SET
  SEG_G = SET;
  stop;
  elseif (a==6) then (yes)
  :SEG_A = SET
  SEG_B = RESET
  SEG_C = SET
  SEG_D = SET
  SEG_E = SET
  SEG_F = SET
  SEG_G = SET;
  stop;
  elseif (a==7) then (yes)
  :SEG_A = SET
  SEG_B = SET
  SEG_C = SET
  SEG_D = RESET
  SEG_E = RESET
  SEG_F = RESET
  SEG_G = RESET;
  stop;
  elseif (a==8) then (yes)
  :SEG_A = SET
  SEG_B = SET
  SEG_C = SET
  SEG_D = SET
  SEG_E = SET
  SEG_F = SET
  SEG_G = SET;
  stop;
  elseif (a==9) then (yes)
  :SEG_A = SET
  SEG_B = SET
  SEG_C = SET
  SEG_D = SET
  SEG_E = RESET
  SEG_F = SET
  SEG_G = SET;
  stop;
endif
stop
@enduml

@startuml
(*)--> if "static uint_8 interrupt_counter <= 9" then
  -->[true] "unit_digit()"
  --> "sevenseg_display(interrupt_counter)
  interrupt_counter++"
  -right-> (*)
else
  ->[false] "second_digit = interrupt_counter/10
  tens_digit(second_digit);
  first_digit = interrupt_counter%10
  unit_digit(first_digit);
  interrupt_counter++;"

-->  if "interrupt_counter>99" then
  -->[true]"interrupt_counter = 0"

  -->[Ending process] (*)
endif

@enduml